# Generated by Django 4.1.1 on 2022-12-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('disponibility', models.DateField()),
                ('price', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('terasseSurface', models.IntegerField()),
                ('totalSurface', models.IntegerField()),
                ('bestOfferName', models.CharField(max_length=100)),
                ('bestOfferAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
