# Generated by Django 4.1.1 on 2022-12-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('odooApartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('disponibility', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('terasseSurface', models.IntegerField()),
                ('totalSurface', models.IntegerField()),
                ('bestOfferName', models.CharField(max_length=100)),
                ('bestOfferAmount', models.IntegerField()),
                ('image', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Appartment',
        ),
    ]
