# Generated by Django 4.1.1 on 2022-12-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odooApartment', '0002_apartment_delete_appartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
