# Generated by Django 4.1.1 on 2022-12-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odooApartment', '0003_alter_stock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='odooApartment.apartment')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
