# Generated by Django 4.1.1 on 2022-12-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odooApartment', '0004_product_delete_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
