# Generated by Django 4.1.1 on 2022-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdooUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('db', models.CharField(max_length=100)),
            ],
        ),
    ]
