# Generated by Django 4.1.1 on 2022-12-16 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('odooConnexion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OdooUser',
            new_name='OdooConnexion',
        ),
    ]
