# Generated by Django 4.1.1 on 2022-12-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('odooConnexion', '0002_rename_odoouser_odooconnexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odooconnexion',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
