# Generated by Django 4.1.1 on 2022-12-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odooConnexion', '0003_alter_odooconnexion_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odooconnexion',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='odooconnexion',
            name='db',
            field=models.CharField(max_length=100, verbose_name='Datebase Name'),
        ),
        migrations.AlterField(
            model_name='odooconnexion',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password or API key'),
        ),
        migrations.AlterField(
            model_name='odooconnexion',
            name='url',
            field=models.CharField(max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='odooconnexion',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
