# Generated by Django 4.1.1 on 2022-12-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odooConnexion', '0006_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
